### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Barnes E",
  "email": "j26515762@gmail.com",
  "password": "shal00j1010",
  "role": "CUSTOMER"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jonathanmwandi6@gmail.com",
    "password": "shal00j1010"
}
