### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Edison Shark",
  "email": "jonathanmwandi6@gmail.com",
  "password": "shal00j1010"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jonathanmwandi6@gmail.com",
    "password": "shal00j1010"
}
