### add to cart
POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NWRiZmFkZi02NGE5LTRjOTAtOGQ4Mi03MTNjN2NkZDM3MTQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpNkBnbWFpbC5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTAzOTAzMzgsImV4cCI6MTc1MDQ3NjczOH0.Q67Neh_URohLrm19MATdn4gRtKvRDtbD1NVxoyTYUck

{
  "productId": "a4c502d2-9c47-49f7-abff-a592bdb46e4c",
  "quantity": 4
}

### delete from the cart
DELETE http://localhost:3000/cart/b0a0b64c-185f-4a0c-85bc-9ba5d8351c50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmJhNGVhNS1hMjM5LTQ5ZDktODA0YS05MmExMWYyNmUzOTciLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTAzNzUwNTUsImV4cCI6MTc1MDQ2MTQ1NX0.lXR8ut7utQNX9cun_v5SraNjQvP75uEf8Uz7EaYOXq4

### checkout cart
POST http://localhost:3000/cart/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MmJhNGVhNS1hMjM5LTQ5ZDktODA0YS05MmExMWYyNmUzOTciLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTAzNzUwNTUsImV4cCI6MTc1MDQ2MTQ1NX0.lXR8ut7utQNX9cun_v5SraNjQvP75uEf8Uz7EaYOXq4
